### ISSUE TITLE
gnmi_cli still does not support Typed value with new gnmi.proto

### ISSUE THREAD

**Issue by dparameswarappa** [openconfig/gnmi#12] opened 2017-10-17 23:01 UTC
Continued from last post... 
When i used the same gnmi_cli with the different server that is using new proto(0.4.0) i dont receive any reply.
o/p:
./gnmi_cli -a 10.33.81.100:6702 -qt s -dt p -pi 10s -q /hello/system/logical-core-percent[cpu-id=5] -client_types gnmi
subscribe:<subscription:<path:<element:"hello" element:"system" element:"logical-core-percent[cpu-id=5]" > > >

It just sits here and waits.

To verify we used a home grown tool with same server we received this below reply.

$ ./gnmic
Server address: 10.33.81.100
Server port: 6702
Enter sensor names...
system logical-core-percent[cpu-id=5]
subscribe { prefix { origin: "caxv-gmathur-01" elem { name: "hello" } } subscription { path { origin: "OriginHello" elem { name: "system" } elem { name: "logical-core-percent" key { key: "cpu-id" value: "5" } } } mode: SAMPLE sample_interval: 2000 heartbeat_interval: 10000 } }

update {
timestamp: 1508267372968000000
prefix {
origin: "Hello"
elem { name: "hello" }
elem { name: "system" }
elem { name: "logical-core-percent" key { key: "cpu-id" value: "5" } } }
update {
path {
origin: "Hello"
elem { name: "cpu-idle" }
}
val { float_val: 100 }
}
}

**Comment by awly** [comment] 2017-10-17 23:14
Duplicate of #11

**Closed by awly** 2017-10-17 23:14 UTC
